import React from 'react';

interface PrivacyPolicyScreenProps {
    onBack: () => void;
}

const PrivacyPolicyScreen: React.FC<PrivacyPolicyScreenProps> = ({ onBack }) => {
    return (
        <div className="animate-fade-in-up text-text-primary-light dark:text-text-primary-dark">
            <button onClick={onBack} className="flex items-center text-accent-light dark:text-accent-dark font-semibold mb-6">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Back to Settings
            </button>
            <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
            <p className="text-sm text-text-secondary-light dark:text-text-secondary-dark mb-6">Last Updated: October 26, 2023</p>

            <div className="space-y-6 text-text-secondary-light dark:text-text-secondary-dark">
                <p>
                    Welcome to EchoVerse. We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application.
                </p>

                <div className="space-y-2">
                    <h2 className="text-xl font-semibold text-text-primary-light dark:text-text-primary-dark">1. Information We Collect</h2>
                    <p>We may collect information about you in a variety of ways. The information we may collect via the App includes:</p>
                    <ul className="list-disc list-inside pl-4">
                        <li><strong>Personal Data:</strong> While we use mock authentication for this demo, a full implementation with services like Firebase would collect personally identifiable information, such as your name, email address, and basic account data from Google or Apple upon sign-in.</li>
                        <li><strong>Journal & Voice Data:</strong> We collect the information you provide directly to us, such as your text notes and recorded voice entries. This is the core data for the App's functionality. Your audio data is stored temporarily to provide the service and is not shared.</li>
                        <li><strong>AI-Generated Data:</strong> We collect and store the analysis generated by our AI service based on your entries, such as detected moods, summaries, and themes. This is linked to your account to provide you with historical insights.</li>
                    </ul>
                </div>
                
                <div className="space-y-2">
                    <h2 className="text-xl font-semibold text-text-primary-light dark:text-text-primary-dark">2. How We Use Your Information</h2>
                    <p>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the App to:</p>
                    <ul className="list-disc list-inside pl-4">
                        <li>Generate personalized AI-driven summaries and insights.</li>
                        <li>Create and manage your account.</li>
                        <li>Track and display your journal history, trends, and streaks.</li>
                        <li>Identify deeper patterns and connections in your entries.</li>
                        <li>Monitor and analyze usage and trends to improve the App.</li>
                    </ul>
                </div>

                <div className="space-y-2">
                    <h2 className="text-xl font-semibold text-text-primary-light dark:text-text-primary-dark">3. Disclosure of Your Information</h2>
                    <p>We do not share your personal information with third parties except as described in this Privacy Policy. We may share information with:</p>
                     <ul className="list-disc list-inside pl-4">
                        <li><strong>Third-Party Service Providers:</strong> We may share your text data with third-party vendors that perform services for us, such as Google for the Generative AI (Gemini) API. Your text note is sent anomymously to generate analysis. Your personal identity is never shared with the AI service. Voice data is processed client-side and is not sent to third parties.</li>
                        <li><strong>By Law or to Protect Rights:</strong> If we believe the release of information about you is necessary to respond to legal process, we may share your information as permitted or required by any applicable law.</li>
                    </ul>
                </div>
                
                 <div className="space-y-2">
                    <h2 className="text-xl font-semibold text-text-primary-light dark:text-text-primary-dark">7. Contact Us</h2>
                    <p>
                        If you have questions or comments about this Privacy Policy, please contact us at: <a href="mailto:support@echoverse.app" className="text-accent-light dark:text-accent-dark hover:underline">support@echoverse.app</a>
                    </p>
                </div>
            </div>
        </div>
    );
};

export default PrivacyPolicyScreen;